version: '3'

services:
  app:
    image: /Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9001:9001"
    environment:
      - URI_BD = mysql://root:root@127.0.0.1:3306/prueba_celsia_internet
      - LOGGING = true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["npm", "start"]

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba_celsia_internet
    volumes:
      - db_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data: